version: '3'

networks:
    default:
        external:
            name: ${EXTERNAL_NET}


services:

    offices:
        image: ruben4test/mgunginx
        container_name: offices
        ports:
            - ${HTTP_WEB_PORT}:80
        restart: on-failure
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ".:/web"
        depends_on:
            - "officesphp"
            - "officescomposer"


    officesphp:
        image: ruben4test/mguphpdev
        container_name: officesphp
        working_dir: "/web"
        environment:
            - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
            - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
            - XDEBUG_REMOTE_CONNECT_BACK=${XDEBUG_REMOTE_CONNECT_BACK}
        restart: on-failure
        volumes:
            - ".:/web"
            - "./var/logs:/var/log/api"


    officescomposer:
        image: composer/composer
        container_name: officescomposer
        volumes:
            - ".:/app"
            - "~/.composer/cache:/tmp/cache"
        command: install --ignore-platform-reqs


    local_housfy_mariadb:
        image: mariadb
        container_name: local_housfy_mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USER}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - ${MARIADB_PORT}:3306


    local_housfy_adminer:
        image: adminer
        container_name: local_housfy_adminer
        restart: on-failure
        depends_on:
            - local_housfy_mariadb
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            ADMINER_DEFAULT_SERVER: local_housfy_mariadb
            ADMINER_DEFAULT_DB_NAME: ${ADMINER_DEFAULT_DB_NAME}
            ADMINER_DESIGN: nette
            ADMINER_PLUGINS: tables-filter tinymce


    local_housfy_redis:
        image: redis:alpine
        container_name: local_housfy_redis
        ports:
            - ${REDIS_PORT}:6379


    local_housfy_rabbitmq:
        container_name: local_housfy_rabbitmq
        image: rabbitmq:3-management-alpine
        restart: on-failure
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBIT_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - ${WEB_RABBIT_PORT}:15672
            - ${RABBIT_PORT}:5672


volumes:

    mariadb_data:

    redis_data:
